;
; Comment
;

; === STACK SEGMENT ===
MyStack segment stack
  DB 64 dup('12345678')
MyStack endS

; === DATA SEGMENT ===
MyData segment
  ; --- Declare your variables here ---
  nlength DW ?
  note DW ?
  timesToPlay DB "How many times should we repeat the main theme?$"
MyData endS


MyCode segment
 Assume CS:Mycode,DS:MyData
;Includes go here
INCLUDE TIME.INC
INCLUDE CONIO.INC
;End of includes
 playNote PROC ;Hertz should be in note, length in centiseconds should be in nlength
  PUSH AX
  PUSH BX
  PUSH CX
  PUSH DX
  ;Prep time divisor
  MOV AL,0B6h
  OUT 43h,AL
  
  ;Calculate time divisor
  MOV DX,0012h
  MOV AX,2870h
  DIV note
  
  ;Set speaker
  OUT 42h,AL
  MOV AL,AH
  OUT 42h,AL
  
  ;Activate pc speaker
  IN AL,61h
  OR AL,00000011b
  OUT 61h,AL
  
  ;Wait time
  MOV AX,10
  CALL DelayFor100ths
  
  POP DX
  POP BX
  POP CX
  POP AX
  RET
  playNote ENDP
 Main PROC
  Start:
   MOV AX, MYDATA
   MOV DS, AX
   ;Start of your code
   MOV AH,9
   LEA DX,timesToPlay
   Int 21h
   CALL InputDecWord
   MOV CX,AX
   DEC CX
   PUSH CX
   MOV note,622
   CALL playNote
   MOV note,659
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,988
   CALL playNote
   MOV note,988
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,659
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,988
   CALL playNote
   MOV note,1109
   CALL playNote
   MOV note,1245
   CALL playNote
   MOV note,1109
   CALL playNote
   MOV note,932
   CALL playNote
   MOV note,988
   CALL playNote
   MOV note,988
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,659
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,988
   CALL playNote
   MOV note,988
   CALL playNote
   MOV note,1109
   CALL playNote
   MOV note,932
   CALL playNote
   MOV note,988
   CALL playNote
   MOV note,1109
   CALL playNote
   MOV note,1319
   CALL playNote
   MOV note,1245
   CALL playNote
   MOV note,1319
   CALL playNote
   MOV note,1109
   CALL playNote
   MOV note,740
   POP CX
   LOOPCAT:
   PUSH CX
   ;JMP LoopCat3
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,831
   CALL playNote
   MOV note,831
   CALL playNote
   MOV note,622
   call playNote
   MOV note,622
   call playNote
   ;Stop playing
   IN AL,61h
   AND AL,11111100b
   OUT 61h,AL
   MOV AX,10
   CALL DelayFor100ths
   MOV note,494
   CALL playNote
   MOV note,494
   Call playNote
   MOV note,554
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,587
   CALL playNote
   MOV note,587
   CALL playNote
   jmp contc
   LoopCat3:
   POP CX
   IN AL,61h
   AND AL,11111100b
   OUT 61h,AL
   LOOP LOOPCAT
   IN AL,61h
   AND AL,11111100b
   OUT 61h,AL
    JMP END01
   
   Contc:
   MOV note,587
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,831
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,831
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,587
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,587
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,587
   CALL playNote
   MOV note,587
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   
   jmp CONTb
   END01:
   JMP END02
   LOOPCAT2:
   JMP LoopCat3
   CONTb:
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,831
   CALL playNote
   MOV note,831
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,622
   ;STOP, DO SPECIAL THING!0,
    MOV AX,10
   ;Stop playing
   IN AL,61h
   AND AL,11111100b
   OUT 61h,AL
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,587
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,494
    MOV AX,10
   ;Stop playing
   IN AL,61h
   AND AL,11111100b
   OUT 61h,AL
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,587
   CALL playNote
   MOV note,587
   CALL playNote
   MOV note,587
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,831
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,831
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,587
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,587
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,587
   CALL playNote
   MOV note,587
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,415
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,415
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,622
   JMP CONTa
   END02:
   JMP END03
   LOOPCAT1:
   JMP LOOPCAT2
   CONTa:
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,659
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,659
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,415
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,659
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,311
   CALL playNote
   MOV note,330
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,415
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,415
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,415
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,466
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,415
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,659
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,659
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,466
   CALL playNote
   MOV note,466
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,415
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,415
   CALL playNote
   IN AL,61h
   AND AL,11111100b
   OUT 61h,AL
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,659
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,659
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,415
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,659
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,311
   CALL playNote
   MOV note,330
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   IN AL,61h
   AND AL,11111100b
   OUT 61h,AL
   MOV note,370
   CALL playNote
   MOV note,415
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,415
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,415
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,466
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,370
   CALL playNote
   MOV note,415
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,659
   CALL playNote
   MOV note,622
   CALL playNote
   MOV note,659
   CALL playNote
   MOV note,740
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,494
   CALL playNote
   MOV note,554
   CALL playNote
   MOV note,554
   CALL playNote
   IN AL,61h
   AND AL,11111100b
   OUT 61h,AL
   POP CX
   JMP LOOPCAT1
  END03:
   CALL DelayFor100ths
   ;Stop playing
   IN AL,61h
   AND AL,11111100b
   OUT 61h,AL
   ;End of your code.
   XOR AX,AX
   XOR BX,BX
   XOR CX,CX
   XOR DX,DX
   MOV AH, 4Ch
   XOR AL, AL
   INT 21h
  Main ENDP
 MyCode endS
 End Start